//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activnost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activnost()
        {
            this.Polzovatel1 = new HashSet<Polzovatel>();
            this.Polzovatel2 = new HashSet<Polzovatel>();
        }
    
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public int IdMeropriyatiya { get; set; }
        public int IdModeratora { get; set; }
        public int DenMeropriyatiya { get; set; }
        public System.DateTime VremyaNachala { get; set; }
    
        public virtual Meropriyatie Meropriyatie { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovatel> Polzovatel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovatel> Polzovatel2 { get; set; }
    }
}
