//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriyatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meropriyatie()
        {
            this.Activnost = new HashSet<Activnost>();
        }
    
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public System.DateTime DataNachala { get; set; }
        public int DlitelnostVDnyah { get; set; }
        public int IdGoroda { get; set; }
        public Nullable<int> IdOrganizatora { get; set; }
        public Nullable<int> IdPobeditelya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activnost> Activnost { get; set; }
        public virtual Gorod Gorod { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual Polzovatel Polzovatel1 { get; set; }
    }
}
