//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationDbContext : DbContext
    {
        private static ApplicationDbContext context;
        public ApplicationDbContext()
            : base("name=ApplicationDbContext")
        {
        }
        public static ApplicationDbContext GetContext()
        {
            if(context == null)
            {
                context = new ApplicationDbContext();
            }
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activnost> Activnost { get; set; }
        public virtual DbSet<Gorod> Gorod { get; set; }
        public virtual DbSet<Meropriyatie> Meropriyatie { get; set; }
        public virtual DbSet<Napravlenie> Napravlenie { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Polzovatel> Polzovatel { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Strana> Strana { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
