//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovatel()
        {
            this.Activnost = new HashSet<Activnost>();
            this.Meropriyatie = new HashSet<Meropriyatie>();
            this.Meropriyatie1 = new HashSet<Meropriyatie>();
            this.Activnost1 = new HashSet<Activnost>();
            this.Activnost2 = new HashSet<Activnost>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Parol { get; set; }
        public string Imya { get; set; }
        public string Familiya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<int> IdPola { get; set; }
        public string Telefon { get; set; }
        public string DataRozdeniya { get; set; }
        public int IdRoli { get; set; }
        public int IdStrani { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<int> IdNapravleniya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activnost> Activnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meropriyatie> Meropriyatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meropriyatie> Meropriyatie1 { get; set; }
        public virtual Napravlenie Napravlenie { get; set; }
        public virtual Pol Pol { get; set; }
        public virtual Role Role { get; set; }
        public virtual Strana Strana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activnost> Activnost1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activnost> Activnost2 { get; set; }
    }
}
